#!/usr/bin/env python3
"""Render the static interface from the same public database exports."""
import json
from pathlib import Path
from html import escape
from datetime import datetime

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'public'
def read(name): return json.loads((PUBLIC / name).read_text())
def e(value): return escape(str(value or ''), quote=True)
guide = read('guide-data.json')
alumni = read('alumni.json')['alumni']
people = read('people.json')['people']
opportunities = read('opportunities.json')['opportunities']
resources = read('data.json')['resources']
events = read('events.json')['events']
stages = guide['roadmap']
short = ['Find your people', 'Find the problem', 'Build a first version', 'Earn your first dollar', 'Find the right funding', 'Make it repeatable']
stage_notes = ['You don’t need an idea to begin.', 'Trade assumptions for conversations.', 'Make one thing useful to one person.', 'Turn a useful result into a paid pilot.', 'Match the capital to your next milestone.', 'Learn what makes customers come back.']
play_names = {'customer-discovery':'Customer discovery','cold-outreach':'Cold outreach','first-dollar':'Your first dollar','email-marketing':'Email marketing'}
CURRENT = 'aria-current="page"'
EXTERNAL = 'target="_blank" rel="noopener noreferrer"'
arrow = '<span aria-hidden="true">↗</span>'

def button(label, href, ghost=False):
    return f'<a class="button {"button-light" if ghost else "button-dark"} slide-button" href="{e(href)}"><span class="slide-label"><span>{e(label)}</span><span aria-hidden="true">{e(label)}</span></span>{arrow}</a>'

def head(title, active='', kind=''):
    nav = ''.join(f'<a href="/{url}.html" {CURRENT if active==key else ""}>{label}</a>' for key,url,label in [('guide','guide','The guide'),('people','alumni','People'),('opportunities','opportunities','Opportunities')])
    menu = ''.join(f'<a href="/{u}.html">{t}{arrow}</a>' for u,t in [('guide','The guide'),('alumni','Alumni directory'),('people','Campus contacts'),('opportunities','Opportunities'),('resources','Resource library'),('events','Events calendar'),('glossary','Startup dictionary'),('contribute','Contribute')])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7f7f2"><meta name="description" content="An independent guide to building at Purdue. Find your next step, meet the people, and discover opportunities."><title>{e(title)} · Purdue Founder Map</title><link rel="icon" href="/assets/map-mark.svg" type="image/svg+xml"><link rel="preload" href="/fonts/instrument-sans.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/map.css"><script src="/map.js" defer></script>{'<script src="/vendor/gsap.min.js" defer></script><script src="/landing-motion.js" defer></script>' if kind=='home' else ''}</head><body data-page="{e(kind)}"><a class="skip" href="#main">Skip to content</a><div class="navigation-progress" aria-hidden="true"></div><header class="header"><a class="brand" href="/" aria-label="Purdue Founder Map home"><img src="/assets/map-mark.svg" width="30" height="30" alt=""><span>Purdue<br>Founder Map<span class="brand-period">.</span></span></a><nav class="primary-nav" aria-label="Primary">{nav}</nav><div class="header-tools"><button class="command-trigger" data-search-open aria-label="Search the map"><svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span>Search</span><kbd>Ctrl K</kbd></button><details class="site-menu"><summary aria-label="More pages"><span class="menu-lines" aria-hidden="true"></span></summary><nav aria-label="More pages">{menu}<a href="/catalog.json">Download all data ↓</a></nav></details></div></header>'''

def foot():
    return '''<footer class="footer"><div class="footer-top"><a class="brand" href="/"><img src="/assets/map-mark.svg" width="30" height="30" alt=""><span>Built here.<br>Go anywhere.</span></a><p>An independent, open-source guide<br>to the Purdue startup community.</p><div><a href="/contribute.html">Make the map better ↗</a><a href="/catalog.json">Download the database ↓</a><a href="https://github.com/sharziki/purdue-founder-map">GitHub ↗</a></div></div><div class="footer-bottom"><span>West Lafayette, Indiana · 40.4237° N, 86.9212° W</span><span>Not affiliated with or endorsed by Purdue University.</span><a href="/contribute.html#sources">Sources &amp; corrections</a></div></footer><dialog class="search-dialog" id="search-dialog" aria-labelledby="search-title"><form method="dialog" class="dialog-bar"><label id="search-title" for="global-search">Search the map</label><button class="icon-button" aria-label="Close search">×</button></form><input id="global-search" type="search" placeholder="A person, a program, a next step…" autocomplete="off"><div id="search-results" class="search-results" aria-live="polite"><a href="/guide.html">Start the founder guide ↗</a><a href="/alumni.html">Explore the alumni directory ↗</a><a href="/opportunities.html">Find an opportunity ↗</a></div><div class="search-footer">Search public profiles, opportunities, and resources.<kbd>ESC</kbd></div></dialog><dialog class="profile-dialog" id="profile-dialog" aria-labelledby="profile-title"><form method="dialog" class="dialog-bar"><span>FROM THE MAP</span><button class="icon-button" aria-label="Close details">×</button></form><div id="profile-content"></div></dialog></body></html>'''

def write(name, content):
    p=PUBLIC/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content.replace('↗', '<svg class="arrow-icon" viewBox="0 0 24 24" width="1em" height="1em" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14"/></svg>'))

def title(kicker, title, desc='', aside=''):
    description = '<p class="page-description">' + desc + '</p>' if desc else ''
    return f'<div class="page-heading"><div><p class="eyebrow">{e(kicker)}</p><h1>{title}</h1>{description}</div>{aside}</div>'

def portrait(item, size=''):
    path=item.get('image')
    if not path and (PUBLIC/f'assets/alumni/{item["id"]}.webp').exists(): path=f'/assets/alumni/{item["id"]}.webp'
    if path: return f'<img class="portrait {size}" src="{e(path)}" alt="" width="56" height="56" loading="lazy">'
    return '<span class="portrait no-portrait" aria-hidden="true"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor"><circle cx="12" cy="8" r="3"/><path d="M5 21v-3a7 7 0 0 1 14 0v3"/></svg></span>'

def alumni_row(item):
    region=item.get('region','')
    if region=='Not listed':region='Location not listed'
    return f'<article class="person-row" id="{e(item["id"])}">{portrait(item)}<div class="person-name"><a href="{e(item["source_url"])}" data-profile="{e(item["id"])}" data-kind="alumni">{e(item["name"])}</a><span>{e(item.get("connection"))}</span></div><div class="person-work"><strong>{e(item["organization"])}</strong><span>{e(item["role"])}</span></div><div class="person-region">{e(region)}</div><span class="pill">{e(item["kind"])}</span><a class="row-arrow" href="{e(item["source_url"])}" data-profile="{e(item["id"])}" data-kind="alumni" aria-label="View {e(item["name"])}">↗</a></article>'

def opportunity_row(item):
    state = ('Due '+datetime.fromisoformat(item['deadline']).strftime('%b %d')) if item.get('deadline') else ('Rolling' if item['application_cycle']=='rolling' else 'Check next cycle')
    return f'<article class="opportunity-row" id="{e(item["id"])}"><div><span class="eyebrow">{e(item["organizer"])}</span><a class="row-title" href="{e(item["apply_url"])}" data-profile="{e(item["id"])}" data-kind="opportunities">{e(item["name"])}</a><p>{e(item["benefit"])}</p></div><div class="op-amount">{e(item.get("amount_text") or item["type"].capitalize())}<span>{e(item["scope"])} · {e(item["stage"])}</span></div><span class="status-label {"status-open" if item["application_cycle"]=="rolling" else ""}">{e(state)}</span><a class="row-arrow" href="{e(item["apply_url"])}" data-profile="{e(item["id"])}" data-kind="opportunities" aria-label="View {e(item["name"])}">↗</a></article>'

def select(name,label,vals):
    return f'<label class="filter-select"><span>{e(label)}</span><select id="{name}"><option value="">All {label.lower()}</option>'+''.join(f'<option value="{e(v)}">{e(v)}</option>' for v in vals)+'</select></label>'

def directory_tools(placeholder,filters, count):
    return f'<div class="directory-toolbar"><label class="directory-search"><svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="directory-search" type="search" placeholder="{e(placeholder)}" aria-label="{e(placeholder)}" autocomplete="off"></label>{filters}<button id="reset-filters" class="text-button" hidden>Reset</button></div><div class="result-meta"><span id="result-count" aria-live="polite">{count}</span><span>Public sources. Real starting points.</span></div><noscript><p class="notice">Here is a selection from the directory. Enable JavaScript to search every record, or <a href="/catalog.json">download the complete data</a>.</p></noscript>'

def home():
    featured_ids=['john-gedmark','akshay-kothari','kendra-bracken-ferguson','don-thompson']
    featured=[next(x for x in alumni if x['id']==i) for i in featured_ids]
    labels=['Find your people','Find a problem','Build a prototype','Get your first customer','Find funding','Keep growing']
    route=''.join(f'<a class="visual-step" href="/guide/{stage["id"]}.html"><span>0{i+1}</span><strong>{labels[i]}</strong>{arrow}</a>' for i,stage in enumerate(stages))
    cards=''.join(f'<a class="founder-card" href="/alumni.html?person={x["id"]}"><div class="founder-image">{portrait(x)}</div><div><span>{e(x["organization"])}</span><h3>{e(x["name"])}</h3></div>{arrow}</a>' for x in featured)
    programs=[('purdue-hackers-microgrants','purdue-hackers.svg','Purdue Hackers','Microgrants','Purdue Hackers · Up to $1,000','grant'),('y-combinator','y-combinator.png','Y Combinator','Y Combinator','Accelerator','yc'),('purdue-innovates-accelerator','innovates.png','Purdue Innovates','Purdue Innovates','Accelerator','innovates')]
    support=''
    for id,logo,org,name,detail,style in programs:
        support+=f'<a class="program-visual program-{style}" href="/opportunities.html?program={id}"><span class="program-category">{e(detail)}</span><div class="program-art"><img src="/assets/orgs/{logo}" alt="{e(org)}" width="160" height="160" loading="lazy"></div><div class="program-bottom"><h3>{name}</h3>{arrow}</div></a>'
    body=f'''<main id="main">
<section class="home-hero shell"><div class="hero-copy"><p class="eyebrow"><span class="live-dot"></span> THE PURDUE FOUNDER GUIDE</p><h1>Start here.<br>Build<br><span class="hero-last">anywhere<span class="gold-dot">.</span></span></h1><p class="hero-description">Your people. Your next step.</p><div class="hero-actions">{button('Explore the guide','/guide.html')}<a class="quiet-link" href="/alumni.html">Find people {arrow}</a></div></div><figure class="hero-art"><img src="/assets/bell-tower-dither.webp" alt="Dithered illustration of Purdue’s Bell Tower" width="1024" height="1536" fetchpriority="high"><figcaption><span class="art-cross">+</span> WEST LAFAYETTE, IN</figcaption></figure><div class="hero-register"><span>An independent, open-source map.</span><div><a href="/alumni.html"><strong>{len(alumni):,}</strong> people</a><span>·</span><a href="/opportunities.html"><strong>{len(opportunities)}</strong> opportunities</a><span>·</span><a href="/resources.html"><strong>{len(resources)}</strong> resources</a></div><a href="#roadmap" class="down-link" aria-label="Explore the roadmap">↓</a></div></section>
<section class="home-route shell" id="roadmap"><div class="section-heading"><div><p class="eyebrow">01 / THE PATH</p><h2>From zero to one.</h2></div><a class="quiet-link" href="/guide.html">The full guide {arrow}</a></div><div class="visual-roadmap"><figure class="prototype-art"><img src="/assets/prototype-dither.webp" width="1200" height="800" alt="Exploded-view illustration of a small satellite prototype" loading="lazy"><figcaption>EVERYTHING STARTS SOMEWHERE.<span>Concept illustration</span></figcaption></figure><nav class="visual-steps" aria-label="Founder roadmap">{route}</nav></div></section>
<section class="home-opps shell" id="directory"><div class="section-heading"><div><p class="eyebrow">02 / A HEAD START</p><h2>Back your ambition.</h2></div><a class="quiet-link" href="/opportunities.html">All opportunities {arrow}</a></div><div class="support-grid">{support}</div><p class="source-caption">Explore programs. Check current terms and eligibility.</p></section>
<section class="home-people shell"><div class="section-heading"><div><p class="eyebrow">03 / YOUR PEOPLE</p><h2>Same starting point.</h2></div><a class="quiet-link" href="/alumni.html">Meet the network {arrow}</a></div><div class="founder-grid">{cards}</div><a class="campus-invite" href="/events.html"><div class="campus-marks"><img src="/assets/orgs/purdue-hackers.svg" width="48" height="48" alt="Purdue Hackers" loading="lazy"><img src="/assets/orgs/buildpurdue.svg" width="90" height="48" alt="buildpurdue" loading="lazy"><img src="/assets/orgs/anvil.png" width="48" height="48" alt="The Anvil" loading="lazy"></div><span>Find your room.</span><strong>Campus events {arrow}</strong></a></section>
<section class="home-close shell"><span class="eyebrow">OVER TO YOU</span><h2>Your move.</h2>{button('Start building','/guide.html')}<span class="close-mark" aria-hidden="true">↗</span></section></main>'''
    write('index.html',head('Start something',kind='home')+body+foot())

def guide_sidebar(active):
    nav=''.join(f'<a href="/guide/{s["id"]}.html" {CURRENT if active==s["id"] else ""}><span>0{i+1}</span>{short[i]}</a>' for i,s in enumerate(stages))
    return f'<aside class="guide-sidebar"><a class="eyebrow" href="/guide.html">THE FOUNDER GUIDE</a><nav aria-label="Guide chapters">{nav}<div class="rail-divider"></div>'+''.join(f'<a href="/playbooks/{k}.html" {CURRENT if active==k else ""}>{v}</a>' for k,v in play_names.items())+'<a href="/glossary.html">Startup dictionary ↗</a></nav><div class="rail-note"><span class="live-dot"></span> Your progress stays<br>on this device.</div></aside>'

def link_list(items):
    return '<div class="reading-list">'+''.join(f'<a href="{e(x["url"])}" {EXTERNAL if x["url"].startswith("https") else ""}><div><strong>{e(x.get("title") or x.get("name"))}</strong><span>{e(x.get("why_read") or x.get("use") or x.get("publisher", ""))}</span></div>{arrow}</a>' for x in items)+'</div>'

def guide_pages():
    cards=''.join(f'<a class="roadmap-step" href="/guide/{s["id"]}.html"><span class="step-node">0{i+1}</span><div><span class="eyebrow">{e(s["id"])}</span><h2>{short[i]}</h2><p>{stage_notes[i]}</p></div><span class="roadmap-cta">Open chapter {arrow}</span></a>' for i,s in enumerate(stages))
    body=f'<main id="main" class="shell guide-overview">{title("A FIELD GUIDE, NOT A FORMULA","From curious<br>to building.","Six stages. Practical next steps. Start where you are.")}<div class="roadmap-layout"><div class="roadmap-stops">{cards}</div><aside class="start-note"><span class="eyebrow">FIRST TIME HERE?</span><img class="guide-prototype" src="/assets/prototype-dither.webp" width="1200" height="800" alt="Concept illustration of a prototype" loading="lazy"><h2>Make a start.</h2>{button("Start at step one","/guide/explore.html")}<div class="note-rule"></div><a href="/events.html">Find a campus event ↗</a><a href="/people.html">Find someone to ask ↗</a></aside></div><section class="playbook-shelf"><div><span class="eyebrow">NEED SOMETHING SPECIFIC?</span><h2>The practical stuff.</h2></div>{link_list([{"title":v,"url":f"/playbooks/{k}.html","use":next(p["goal"] for p in guide["playbooks"] if p["id"]==k)} for k,v in play_names.items()])}</section></main>'
    write('guide.html',head('The guide','guide','guide')+body+foot())
    for i,s in enumerate(stages):
        tools=[dict(x,url={'/people.json':'/people.html','/alumni.json':'/alumni.html','/events.json':'/events.html'}.get(x['url'],x['url'])) for x in guide['tools'] if x['id'] in s['tool_ids']]
        reading=[x for x in guide['reading_links'] if x['id'] in s['reading_link_ids']]
        checks=''.join(f'<label class="action-check"><input type="checkbox" data-progress="{s["id"]}-{n}"><span class="check-box" aria-hidden="true"></span><span>{e(a)}</span></label>' for n,a in enumerate(s['actions']))
        pbs=[{'title':play_names[k],'url':f'/playbooks/{k}.html','use':'A step-by-step playbook'} for k in s['playbook_ids']]
        nxt=f'<a class="next-chapter" href="/guide/{stages[i+1]["id"]}.html"><span>UP NEXT</span><strong>{short[i+1]}</strong>{arrow}</a>' if i<5 else f'<a class="next-chapter" href="/opportunities.html"><span>KEEP BUILDING</span><strong>Find your next opportunity</strong>{arrow}</a>'
        content=f'<main id="main" class="shell guide-layout">{guide_sidebar(s["id"])}<article class="chapter"><a class="back-link" href="/guide.html">← All six stages</a><p class="eyebrow">CHAPTER 0{i+1} / 06</p><h1>{short[i]}.</h1><p class="chapter-lead">{e(s["question"])}</p><section><h2>Your next moves</h2><div class="action-list">{checks}</div></section><aside class="outcome"><span class="eyebrow">YOU’RE READY TO MOVE ON WHEN</span><p>{e(s["exit_signal"])}</p></aside><section><h2>Go a little deeper</h2>{link_list(pbs)}</section><section><h2>Useful tools &amp; places</h2>{link_list(tools)}</section><section><h2>Worth your time</h2>{link_list(reading[:4])}</section>{nxt}</article></main>'
        write(f'guide/{s["id"]}.html',head(short[i],'guide','chapter')+content+foot())
    for p in guide['playbooks']:
        steps=''.join(f'<div class="playbook-step"><span>0{x["order"]}</span><div><p>{e(x["action"])}</p><small>MAKE THIS: {e(x["output"])}</small></div></div>' for x in p['steps'])
        templates=''.join(f'<div class="template"><div><span class="eyebrow">{e(t["use"])}</span><button class="text-button" data-copy="{e(t["id"])}">Copy template</button></div><pre id="{e(t["id"])}">Subject: {e(t["subject"])}\n\n{e(t["body"])}</pre></div>' for t in p.get('templates',[]))
        if p.get('sample_offer'):templates+=f'<div class="template"><span class="eyebrow">AN OFFER TO ADAPT</span><p>{e(p["sample_offer"])}</p></div>'
        sources=[guide['sources'][k] for k in p['source_ids']]
        content=f'<main id="main" class="shell guide-layout">{guide_sidebar(p["id"])}<article class="chapter"><a class="back-link" href="/guide.html">← The founder guide</a><p class="eyebrow">PRACTICAL PLAYBOOK · {e(p["timebox"])}</p><h1>{play_names[p["id"]]}.</h1><p class="chapter-lead">{e(p["goal"])}</p><section class="playbook-steps">{steps}</section>{templates}<section><h2>What to watch out for</h2><ul class="plain-list">'+''.join(f'<li>{e(x)}</li>' for x in p['avoid'])+f'</ul></section><section><h2>Keep reading</h2>{link_list(sources)}</section><a class="next-chapter" href="/alumni.html"><span>PUT IT INTO PRACTICE</span><strong>Find a relevant person</strong>{arrow}</a></article></main>'
        write(f'playbooks/{p["id"]}.html',head(play_names[p['id']],'guide','chapter')+content+foot())

def directory_pages():
    selected=sorted(alumni,key=lambda x:(0 if x.get('highlights') else 1,x.get('highlight_order',999),x['name']))
    filters=select('kind-filter','Roles',['Founder','Investor','Operator'])+select('region-filter','Regions',['Bay Area','New York','Indiana','Midwest'])+select('tag-filter','Tags',['Venture-backed','VC investor','Y Combinator','Funded startup'])+'<label class="filter-select"><span>Sort</span><select id="sort-filter"><option value="">Featured first</option value="name">Name A–Z</option><option value="organization">Organization A–Z</option></select></label>'
    body=f'<main id="main" class="shell directory-page">{title("THE PURDUE NETWORK","Purdue people.","Research the founders, investors, and operators who started here.")}<div class="page-tabs"><a class="active" href="/alumni.html">Alumni <span>{len(alumni):,}</span></a><a href="/people.html">Campus contacts <span>{len(people)}</span></a><a class="tab-end" href="/alumni.json">Download JSON ↓</a></div>{directory_tools("Search a name, company, or field…",filters,f"{len(alumni):,} public profiles")}<div class="table-labels"><span>PERSON</span><span>ORGANIZATION / ROLE</span><span>LOCATION</span><span>TYPE</span></div><div id="directory-results" class="people-list">'+''.join(alumni_row(x) for x in selected[:24])+f'</div><div class="load-more"><button class="button button-light" id="load-more">Show more people ↓</button></div><p class="directory-disclosure">Profiles reflect public sources, including historical roles. A listing does not imply availability for introductions. Open a profile to see its evidence.</p></main>'
    write('alumni.html',head('The alumni network','people','alumni')+body+foot())
    campus=''.join(f'<article class="campus-card">{portrait(x)}<div><span class="eyebrow">{e(x["lane"])}</span><a href="{e(x["url"])}" data-profile="{e(x["id"])}" data-kind="people">{e(x["name"])}</a><span class="campus-org">{e(x["organization"])}</span><p>{e(x["helps"])}</p></div><a class="row-arrow" href="{e(x["url"])}" data-profile="{e(x["id"])}" data-kind="people" aria-label="View {e(x["name"])}">↗</a></article>' for x in people)
    body=f'<main id="main" class="shell directory-page">{title("YOUR CAMPUS STARTING POINTS","Ask a real person.","The people behind Purdue’s programs, communities, and capital.")}<div class="page-tabs"><a href="/alumni.html">Alumni <span>{len(alumni):,}</span></a><a class="active" href="/people.html">Campus contacts <span>{len(people)}</span></a><a class="tab-end" href="/people.json">Download JSON ↓</a></div>{directory_tools("Search a person, program, or topic…",select("kind-filter","Stages",sorted(set(x["lane"] for x in people))),f"{len(people)} campus contacts")}<div class="campus-grid" id="directory-results">{campus}</div></main>'
    write('people.html',head('Campus contacts','people','people')+body+foot())
    filters=select('kind-filter','Types',sorted(set(x['type'] for x in opportunities)))+select('region-filter','Regions',['Purdue','Indiana','Midwest','US','Global'])+select('stage-filter','Stages',['Explore','Validate','Build','Launch','Fund','Scale'])
    initial=sorted(opportunities,key=lambda x:(0 if x['scope']=='Purdue' else 1,x['name']))
    body=f'<main id="main" class="shell directory-page">{title("YOUR NEXT OPENING","Opportunities.","Grants, accelerators, capital, and support for wherever you are now.",button("Export the list","/opportunities.json",True))}<div class="quick-filters" aria-label="Quick filters"><button class="active" data-quick="">Everything <span>{len(opportunities)}</span></button><button data-quick="Purdue">At Purdue</button><button data-quick="grant">Grants</button><button data-quick="accelerator">Accelerators</button><button data-quick="investment">Capital</button></div>{directory_tools("Search a program, field, or benefit…",filters,f"{len(opportunities)} opportunities")}<div class="opportunity-list" id="directory-results">'+''.join(opportunity_row(x) for x in initial[:20])+f'</div><div class="load-more"><button class="button button-light" id="load-more">Show more opportunities ↓</button></div><p class="directory-disclosure">Program amounts and terms come from linked sources. Eligibility and application windows change; check the organizer’s page before applying.</p></main>'
    write('opportunities.html',head('Opportunities','opportunities','opportunities')+body+foot())
    filters=select('kind-filter','Categories',sorted(set(x['category'] for x in resources)))
    rows=''.join(f'<a class="resource-row" href="{e(x["url"])}" target="_blank" rel="noopener noreferrer"><span class="pill">{e(x["category"])}</span><div><h2>{e(x["name"])}</h2><p>{e(x["summary"])}</p></div>{arrow}</a>' for x in resources[:30])
    body=f'<main id="main" class="shell directory-page">{title("THE RESOURCE LIBRARY","Keep good things<br>within reach.","Campus communities, founder tools, and useful places to go next.")}{directory_tools("Search resources…",filters,f"{len(resources)} resources")}<div id="directory-results">{rows}</div><div class="load-more"><button class="button button-light" id="load-more">Show more resources ↓</button></div></main>'
    write('resources.html',head('Resources',kind='resources')+body+foot())

def other_pages():
    terms=sorted(guide['glossary'],key=lambda x:x['term'])
    rows=''.join(f'<details class="glossary-term" id="{e(x["id"])}"><summary><span>{e(x["term"])}</span><span class="plus" aria-hidden="true">+</span></summary><p>{e(x["definition"])}</p><p class="term-example">{e(x.get("example"))}</p>{link_list([guide["sources"][sid] for sid in x.get("source_ids",[])])}</details>' for x in terms)
    body=f'<main id="main" class="shell glossary-page">{title("THE STARTUP DICTIONARY","Plain English,<br>please.","The words you’ll hear, without the assumption you already know them.")}<label class="directory-search glossary-search"><svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="glossary-search" type="search" placeholder="Look up a term…" aria-label="Look up a term"></label><div id="glossary-list">{rows}</div><p class="empty-state" id="glossary-empty" hidden>No matching terms. Try another word.</p></main>'
    write('glossary.html',head('Startup dictionary','guide','glossary')+body+foot())
    agenda=''.join(f'<a class="event-row" href="{e(x["url"])}"><time datetime="{e(x["starts_at"])}"><strong>{datetime.fromisoformat(x["starts_at"]).strftime("%d")}</strong><span>{datetime.fromisoformat(x["starts_at"]).strftime("%b")}</span></time><div><span class="eyebrow">{e(x["host"])}</span><h3>{e(x["title"])}</h3><p>{e(x.get("venue"))}</p></div>{arrow}</a>' for x in events[:12])
    body=f'<main id="main" class="shell events-page">{title("MAKE A LITTLE ROOM","Founder events.","Founder talks, build nights, and conversations worth showing up for.",button("Download calendar","/founder-events.ics",True))}<div class="calendar-layout"><details class="calendar-panel" open><summary>Choose a date <span aria-hidden="true">+</span></summary><div class="calendar-inner"><div class="calendar-head"><h2 id="calendar-month">Upcoming events</h2><div><button class="icon-button" id="calendar-prev" aria-label="Previous month">←</button><button class="icon-button" id="calendar-next" aria-label="Next month">→</button></div></div><div class="calendar-weekdays" aria-hidden="true">'+''.join(f'<span>{d}</span>' for d in ['M','T','W','T','F','S','S'])+f'</div><div id="calendar-grid"></div><p class="calendar-key"><span class="live-dot"></span> A day with something happening</p><button class="text-button" id="calendar-all">Show all upcoming events</button><p class="calendar-help">Times shown in Purdue’s Eastern time zone. Import the .ics file into Google, Apple, or Outlook Calendar.</p></div></details><section class="agenda"><div class="agenda-heading"><span class="eyebrow" id="agenda-title">UPCOMING EVENTS</span><label><input type="checkbox" id="campus-only"> Campus only</label></div><div id="events-list">{agenda}</div><noscript><p><a href="/founder-events.ics">Download the complete event calendar.</a></p></noscript></section></div></main>'
    write('events.html',head('Events calendar',kind='events')+body+foot())
    body=f'''<main id="main" class="shell contribute-page">{title("AN OPEN MAP","Better together.","Know a person, program, or useful link we missed? Add it to the map.")}<div class="contribution-layout"><div><a class="contribution-row" href="https://github.com/sharziki/purdue-founder-map/issues/new?template=resource.yml"><span>01</span><div><h2>Add a resource or opportunity</h2><p>Bring the official link and who it’s for.</p></div>{arrow}</a><a class="contribution-row" href="https://github.com/sharziki/purdue-founder-map/issues/new?template=alumnus.yml"><span>02</span><div><h2>Add someone to the network</h2><p>A public profile and their Purdue connection.</p></div>{arrow}</a><a class="contribution-row" href="https://github.com/sharziki/purdue-founder-map/issues/new?template=correction.yml"><span>03</span><div><h2>Make a correction</h2><p>Changed roles, closed programs, and broken links.</p></div>{arrow}</a></div><aside class="start-note"><span class="eyebrow">BUILD WITH THE DATA</span><h2>Take the<br>whole map.</h2><p>Public JSON. No account. No API key. Use the data in your own project.</p>{button('Download all data','/catalog.json')}<a href="https://github.com/sharziki/purdue-founder-map/blob/main/docs/DATA-API.md">Read the data docs ↗</a></aside></div><section class="sources-note" id="sources"><h2>A note on sources.</h2><p>We link each record to its public source. Historical roles keep their dates, funding belongs to the named company, and missing facts stay missing. Corrections are welcome.</p><p>This is an independent project. Purdue University and the organizations listed have not endorsed it. Code and original writing are open source under MIT; linked content and trademarks belong to their owners.</p><a class="quiet-link" href="https://github.com/sharziki/purdue-founder-map/blob/main/CONTRIBUTING.md">Contributing guide ↗</a></section></main>'''
    write('contribute.html',head('Contribute',kind='contribute')+body+foot())

if __name__=='__main__':
    home();guide_pages();directory_pages();other_pages()
    print('Rendered 19 pages from public data exports')
